#!/bin/bash

# Define your directories (change these if your folders are named differently)
BENIGN_DIR="capturas/benign"
ATTACK_DIR="capturas/attack"

# Define the final master output files
BENIGN_MASTER="super_baseline_benign.csv"
ATTACK_MASTER="super_baseline_attack.csv"

# 1. Create the master files and inject the CSV header (only once!)
echo "packet_number,interface_id,src_mac,global_delta_ms,source_delta_ms" > "$BENIGN_MASTER"
echo "packet_number,interface_id,src_mac,global_delta_ms,source_delta_ms" > "$ATTACK_MASTER"

# 2. Process Benign PCAPs
echo "[*] Starting Benign Dataset Extraction..."
for file in "$BENIGN_DIR"/*.pcap; do
    # Check if file exists to prevent errors on empty directories
    if [ -f "$file" ]; then
        echo "  -> Processing: $file"
        # Run tshark silently (-q) with your updated Lua script
        tshark -r "$file" -q -X lua_script:scripts/jitter_filter.lua 
        
        # Append data (skipping the 1st row header) into the master file
        tail -n +2 jitter_output_filtered.csv >> "$BENIGN_MASTER"
    fi
done

# 3. Process Attack PCAPs
echo "[*] Starting Attack Dataset Extraction..."
for file in "$ATTACK_DIR"/*.pcap; do
    if [ -f "$file" ]; then
        echo "  -> Processing: $file"
        tshark -r "$file" -q -X lua_script:scripts/jitter_filter.lua 
        
        tail -n +2 jitter_output_filtered.csv >> "$ATTACK_MASTER"
    fi
done

# 4. Clean up the temporary file generated by the Lua script
if [ -f "jitter_output_filtered.csv" ]; then
    rm jitter_output_filtered.csv
fi

echo "[+] Extraction Complete!"
echo "    -> Benign data saved to: $BENIGN_MASTER"
echo "    -> Attack data saved to: $ATTACK_MASTER"
